baseurl: uophysicsdemos/
url: https://utilisable.github.io/
plugins:
  - jekyll-relative-links
  - jekyll_picture_tag
relative_links:
  enabled: true
  collections: true

# theme: minimal-mistakes-jekyll

collections:
  demos:
    output: true
  categories:
    output: true
    permalink: /:collection/:name
    sort_by: pira
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

picture:
  source: "assets/images/fullsize"
  output: "assets/images/generated"
  ignore_missing_images: true

defaults:
  -
    scope:
      path: ""
      type: "demos"
    values:
      layout: default
      share: false
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: category
      share: false
         
  
